Update repositories.yaml
mozilla/probe-scraper pull request #489
Opened 2022-09-12 20:39 UTC by evoluchico

Add viu-politica app to repositories.yaml for probe scraper to validate and publish its metrics

2022-09-12 20:57 UTC, chutten requested changes

2022-09-12 20:57 UTC, chutten commented on repositories.yaml
> +      - viu.politica.dev
If this is something you can control the channels of yourself, there's no need to specify channels here at all.

2022-09-12 20:57 UTC, chutten commented on repositories.yaml
> +      This is a "spin-off" of the Mozilla YouTube RegretsReporter extension. It is an opt-in browser extension where users can anonymously tag videos related to the 2022 Brazilian Elections.
It's a multi-line field, so let's keep column widths down.

```suggestion
      This is a "spin-off" of the Mozilla YouTube RegretsReporter extension.
      It is an opt-in browser extension where users can anonymously tag videos related to the 2022 Brazilian Elections.
```

2022-09-12 20:57 UTC, chutten commented on repositories.yaml
> +- app_name: viu_politica
I believe this is missing some fields that'll allow this to properly run (v1_name and app_id, specifically). Did you happen to test this? Maybe with a command like `python -m probe_scraper.runner --glean --glean-repo viu_politica`?

2022-09-19 13:22 UTC, Dexterp37 commented
Closed in favour of #496

2022-09-19 13:22 UTC, closed without merging