[no-bug] Adding some commits to skip from gecko
mozilla/probe-scraper pull request #676
Opened 2024-01-09 21:42 UTC by travis79

Some gecko metrics.yaml files seemed to be missing from certain commits in my local dry-runs, not sure exactly why but these are the commits that need to be skipped.

2024-01-09 21:50 UTC, travis79 commented
cc @badboy what are your thoughts on this? Is this normal due to some uplifts or something? Is there something we can do to catch and automate this sort of thing?

2024-01-10 10:03 UTC, badboy commented
A full dry-run is LOOOOONG, which is why we don't do it in CI.
It's also not even necessarily exactly what runs in airflow, so it might still not be perfect anyway.

As said in channel:
adding so many skip commits feels wrong, so maybe we should look into how to handle that better; but if that clears it up for the time being I won't stand in the way of course
but we should involve other DEs for visibility

2024-01-10 10:35 UTC, badboy requested changes
The ACTUAL dry-run you want to be running is this:

```
python3 -m probe_scraper.runner --dry-run --cache-dir tmp/cache --out-dir tmp/out --glean --glean-url=https://github.com/mozilla/gecko-dev --output-bucket=gs://probe-scraper-prod-artifacts/ --glean-limit-date=2024-01-09 --update
```

because that closely resembles what is run nightly in airflow.
Notice the `glean-limit-date` (and update). That teaches probe-scraper to go back at most to that date. We incrementally add new metrics and don't have to re-parse old commits.
Yes, that means a dry-run over everything in gecko-dev won't work as is.

I don't think fixing that dry-run-over-everything case is worth it here.
It will happen again in the future and we won't notice.

So really the next steps should be:
* Document that one should dry-run with a limit-date
* Require from everyone to include the exact command they ran when a dry-run failed.

2024-01-10 14:05 UTC, travis79 commented
> The ACTUAL dry-run you want to be running is this:
> 
> ```
> python3 -m probe_scraper.runner --dry-run --cache-dir tmp/cache --out-dir tmp/out --glean --glean-url=https://github.com/mozilla/gecko-dev --output-bucket=gs://probe-scraper-prod-artifacts/ --glean-limit-date=2024-01-09 --update
> ```
> 
> because that closely resembles what is run nightly in airflow. Notice the `glean-limit-date` (and update). That teaches probe-scraper to go back at most to that date. We incrementally add new metrics and don't have to re-parse old commits. Yes, that means a dry-run over everything in gecko-dev won't work as is.
> 
> I don't think fixing that dry-run-over-everything case is worth it here. It will happen again in the future and we won't notice.
> 
> So really the next steps should be:
> 
>     * Document that one should dry-run with a limit-date
> 
>     * Require from everyone to include the exact command they ran when a dry-run failed.

Oh, I ran that plenty of times....  but I've had unusual things (like commits that need skipped) show up after a PR has landed that breaks probe-scraper so I've gotten into the habit of doing full dry-runs locally to give myself some piece of mind.

2024-01-11 09:24 UTC, badboy commented
glean-limit-date is set for the nightly run: https://github.com/mozilla/telemetry-airflow/blob/03274fdad2ade74de6b51a36e4e4fb7f15985240/dags/probe_scraper.py#L169-L173

2024-01-11 13:40 UTC, closed without merging

2024-01-11 13:40 UTC, travis79 commented
Based on your assurances that this isn't something that could break in production thanks to the `--glean-limit-date`, I'm going to close this PR as unnecessary.