feat: Add Backstage app
mozilla/probe-scraper pull request #826
Opened 2024-11-01 19:11 UTC by quiiver

Adding our new backstage app

2024-11-01 22:22 UTC, whd commented on repositories.yaml
> +        app_id: moz_backstage
We don't yet require this value in CI/make it required in the schema but you need to set retention for this app e.g.:
```yaml
    moz_pipeline_metadata_defaults:
      expiration_policy:
        delete_after_days: 400
```

2024-11-04 09:18 UTC, badboy commented
Fixing the treeherder issue in https://github.com/mozilla/probe-scraper/pull/827

2026-08-03 10:03 UTC, badboy requested changes
Isn't this a Glean.js-powered app?
If so this should have

```
    dependencies:
      - glean-js
```

2026-08-20 08:11 UTC, badboy approved these changes

2026-08-20 08:15 UTC, merged